FROM python:3.11-alpine

WORKDIR /app

# Kopeeri requirements enne koodi
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Nüüd kopeeri kood
COPY . .

EXPOSE 5000

CMD ["python", "app.py"]
